apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-e2e-pipeline-run-
spec:
  pipelineRef:
    name: tekton-e2e-pipeline
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: jingyi-wang-tekton-e2e-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/jingyi-wang-tekton-e2e-app
    - name: image-repo
      value: quay.io/wangjingyi_ibm/tekton-e2e-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
