apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-pipeline-run-
spec:
  pipelineRef:
    name: buildah-pipeline
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: express-sample-app
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/jingyi-wang-tekton-buildah-assignment
    - name: image-repo
      value: quay.io/wangjingyi_ibm/tekton-buildah-assignment-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
